@startuml

'left to right direction

package component {

}

package components {

}

package components.appointment {

}

package components.budgets {

}

package components.scheduler {

}

package components.studies {

}

package components.teeth {

}

package interceptors {

}

package model {

}

package pages {

}

package pages.appointments {

}

package pages.budgets {

}

package pages.dashboard {

}

package pages.login {

}

package pages.patients {

}

package pages.studies {

}

package pages.treatments {

}

package pages.users {

}

package services {
}







@enduml