@startuml

package application.services {

}

package application.mappers {

}

package domain.model {

}

package domain.port.in {

}

package domain.port.out {

}

package infraestructure.adapter.in.controller {

}

package infraestructure.adapter.out.mail {

}

package infraestructure.adapter.out.persistence {

}

package infraestructure.adapter.out.report {

}

package infraestructure.adapter.out.signer {

}


package infraestructure.config {

}


@enduml